python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\0.edgelist --output scripts\node2vec\emb\Covid\mers\0.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\1.edgelist --output scripts\node2vec\emb\Covid\mers\1.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\100.edgelist --output scripts\node2vec\emb\Covid\mers\100.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\102.edgelist --output scripts\node2vec\emb\Covid\mers\102.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\103.edgelist --output scripts\node2vec\emb\Covid\mers\103.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\104.edgelist --output scripts\node2vec\emb\Covid\mers\104.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\105.edgelist --output scripts\node2vec\emb\Covid\mers\105.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\107.edgelist --output scripts\node2vec\emb\Covid\mers\107.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\108.edgelist --output scripts\node2vec\emb\Covid\mers\108.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\109.edgelist --output scripts\node2vec\emb\Covid\mers\109.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\111.edgelist --output scripts\node2vec\emb\Covid\mers\111.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\112.edgelist --output scripts\node2vec\emb\Covid\mers\112.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\113.edgelist --output scripts\node2vec\emb\Covid\mers\113.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\114.edgelist --output scripts\node2vec\emb\Covid\mers\114.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\115.edgelist --output scripts\node2vec\emb\Covid\mers\115.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\116.edgelist --output scripts\node2vec\emb\Covid\mers\116.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\117.edgelist --output scripts\node2vec\emb\Covid\mers\117.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\118.edgelist --output scripts\node2vec\emb\Covid\mers\118.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\119.edgelist --output scripts\node2vec\emb\Covid\mers\119.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\12.edgelist --output scripts\node2vec\emb\Covid\mers\12.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\120.edgelist --output scripts\node2vec\emb\Covid\mers\120.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\121.edgelist --output scripts\node2vec\emb\Covid\mers\121.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\122.edgelist --output scripts\node2vec\emb\Covid\mers\122.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\124.edgelist --output scripts\node2vec\emb\Covid\mers\124.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\125.edgelist --output scripts\node2vec\emb\Covid\mers\125.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\126.edgelist --output scripts\node2vec\emb\Covid\mers\126.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\127.edgelist --output scripts\node2vec\emb\Covid\mers\127.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\128.edgelist --output scripts\node2vec\emb\Covid\mers\128.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\129.edgelist --output scripts\node2vec\emb\Covid\mers\129.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\13.edgelist --output scripts\node2vec\emb\Covid\mers\13.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\130.edgelist --output scripts\node2vec\emb\Covid\mers\130.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\131.edgelist --output scripts\node2vec\emb\Covid\mers\131.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\132.edgelist --output scripts\node2vec\emb\Covid\mers\132.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\134.edgelist --output scripts\node2vec\emb\Covid\mers\134.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\135.edgelist --output scripts\node2vec\emb\Covid\mers\135.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\136.edgelist --output scripts\node2vec\emb\Covid\mers\136.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\137.edgelist --output scripts\node2vec\emb\Covid\mers\137.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\138.edgelist --output scripts\node2vec\emb\Covid\mers\138.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\139.edgelist --output scripts\node2vec\emb\Covid\mers\139.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\14.edgelist --output scripts\node2vec\emb\Covid\mers\14.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\140.edgelist --output scripts\node2vec\emb\Covid\mers\140.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\141.edgelist --output scripts\node2vec\emb\Covid\mers\141.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\142.edgelist --output scripts\node2vec\emb\Covid\mers\142.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\144.edgelist --output scripts\node2vec\emb\Covid\mers\144.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\145.edgelist --output scripts\node2vec\emb\Covid\mers\145.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\147.edgelist --output scripts\node2vec\emb\Covid\mers\147.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\148.edgelist --output scripts\node2vec\emb\Covid\mers\148.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\149.edgelist --output scripts\node2vec\emb\Covid\mers\149.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\15.edgelist --output scripts\node2vec\emb\Covid\mers\15.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\150.edgelist --output scripts\node2vec\emb\Covid\mers\150.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\151.edgelist --output scripts\node2vec\emb\Covid\mers\151.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\152.edgelist --output scripts\node2vec\emb\Covid\mers\152.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\153.edgelist --output scripts\node2vec\emb\Covid\mers\153.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\154.edgelist --output scripts\node2vec\emb\Covid\mers\154.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\155.edgelist --output scripts\node2vec\emb\Covid\mers\155.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\156.edgelist --output scripts\node2vec\emb\Covid\mers\156.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\158.edgelist --output scripts\node2vec\emb\Covid\mers\158.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\159.edgelist --output scripts\node2vec\emb\Covid\mers\159.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\16.edgelist --output scripts\node2vec\emb\Covid\mers\16.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\160.edgelist --output scripts\node2vec\emb\Covid\mers\160.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\162.edgelist --output scripts\node2vec\emb\Covid\mers\162.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\163.edgelist --output scripts\node2vec\emb\Covid\mers\163.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\164.edgelist --output scripts\node2vec\emb\Covid\mers\164.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\165.edgelist --output scripts\node2vec\emb\Covid\mers\165.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\166.edgelist --output scripts\node2vec\emb\Covid\mers\166.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\168.edgelist --output scripts\node2vec\emb\Covid\mers\168.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\169.edgelist --output scripts\node2vec\emb\Covid\mers\169.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\170.edgelist --output scripts\node2vec\emb\Covid\mers\170.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\171.edgelist --output scripts\node2vec\emb\Covid\mers\171.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\174.edgelist --output scripts\node2vec\emb\Covid\mers\174.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\175.edgelist --output scripts\node2vec\emb\Covid\mers\175.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\176.edgelist --output scripts\node2vec\emb\Covid\mers\176.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\177.edgelist --output scripts\node2vec\emb\Covid\mers\177.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\179.edgelist --output scripts\node2vec\emb\Covid\mers\179.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\180.edgelist --output scripts\node2vec\emb\Covid\mers\180.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\183.edgelist --output scripts\node2vec\emb\Covid\mers\183.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\185.edgelist --output scripts\node2vec\emb\Covid\mers\185.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\186.edgelist --output scripts\node2vec\emb\Covid\mers\186.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\188.edgelist --output scripts\node2vec\emb\Covid\mers\188.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\189.edgelist --output scripts\node2vec\emb\Covid\mers\189.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\19.edgelist --output scripts\node2vec\emb\Covid\mers\19.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\190.edgelist --output scripts\node2vec\emb\Covid\mers\190.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\191.edgelist --output scripts\node2vec\emb\Covid\mers\191.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\192.edgelist --output scripts\node2vec\emb\Covid\mers\192.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\193.edgelist --output scripts\node2vec\emb\Covid\mers\193.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\194.edgelist --output scripts\node2vec\emb\Covid\mers\194.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\195.edgelist --output scripts\node2vec\emb\Covid\mers\195.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\196.edgelist --output scripts\node2vec\emb\Covid\mers\196.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\198.edgelist --output scripts\node2vec\emb\Covid\mers\198.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\199.edgelist --output scripts\node2vec\emb\Covid\mers\199.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\2.edgelist --output scripts\node2vec\emb\Covid\mers\2.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\20.edgelist --output scripts\node2vec\emb\Covid\mers\20.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\200.edgelist --output scripts\node2vec\emb\Covid\mers\200.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\201.edgelist --output scripts\node2vec\emb\Covid\mers\201.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\21.edgelist --output scripts\node2vec\emb\Covid\mers\21.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\210.edgelist --output scripts\node2vec\emb\Covid\mers\210.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\216.edgelist --output scripts\node2vec\emb\Covid\mers\216.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\217.edgelist --output scripts\node2vec\emb\Covid\mers\217.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\218.edgelist --output scripts\node2vec\emb\Covid\mers\218.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\219.edgelist --output scripts\node2vec\emb\Covid\mers\219.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\22.edgelist --output scripts\node2vec\emb\Covid\mers\22.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\221.edgelist --output scripts\node2vec\emb\Covid\mers\221.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\222.edgelist --output scripts\node2vec\emb\Covid\mers\222.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\223.edgelist --output scripts\node2vec\emb\Covid\mers\223.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\224.edgelist --output scripts\node2vec\emb\Covid\mers\224.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\225.edgelist --output scripts\node2vec\emb\Covid\mers\225.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\227.edgelist --output scripts\node2vec\emb\Covid\mers\227.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\228.edgelist --output scripts\node2vec\emb\Covid\mers\228.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\229.edgelist --output scripts\node2vec\emb\Covid\mers\229.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\23.edgelist --output scripts\node2vec\emb\Covid\mers\23.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\230.edgelist --output scripts\node2vec\emb\Covid\mers\230.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\231.edgelist --output scripts\node2vec\emb\Covid\mers\231.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\232.edgelist --output scripts\node2vec\emb\Covid\mers\232.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\233.edgelist --output scripts\node2vec\emb\Covid\mers\233.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\234.edgelist --output scripts\node2vec\emb\Covid\mers\234.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\235.edgelist --output scripts\node2vec\emb\Covid\mers\235.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\236.edgelist --output scripts\node2vec\emb\Covid\mers\236.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\237.edgelist --output scripts\node2vec\emb\Covid\mers\237.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\238.edgelist --output scripts\node2vec\emb\Covid\mers\238.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\239.edgelist --output scripts\node2vec\emb\Covid\mers\239.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\240.edgelist --output scripts\node2vec\emb\Covid\mers\240.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\248.edgelist --output scripts\node2vec\emb\Covid\mers\248.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\249.edgelist --output scripts\node2vec\emb\Covid\mers\249.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\25.edgelist --output scripts\node2vec\emb\Covid\mers\25.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\250.edgelist --output scripts\node2vec\emb\Covid\mers\250.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\251.edgelist --output scripts\node2vec\emb\Covid\mers\251.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\252.edgelist --output scripts\node2vec\emb\Covid\mers\252.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\253.edgelist --output scripts\node2vec\emb\Covid\mers\253.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\254.edgelist --output scripts\node2vec\emb\Covid\mers\254.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\256.edgelist --output scripts\node2vec\emb\Covid\mers\256.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\257.edgelist --output scripts\node2vec\emb\Covid\mers\257.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\26.edgelist --output scripts\node2vec\emb\Covid\mers\26.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\29.edgelist --output scripts\node2vec\emb\Covid\mers\29.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\32.edgelist --output scripts\node2vec\emb\Covid\mers\32.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\33.edgelist --output scripts\node2vec\emb\Covid\mers\33.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\34.edgelist --output scripts\node2vec\emb\Covid\mers\34.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\38.edgelist --output scripts\node2vec\emb\Covid\mers\38.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\39.edgelist --output scripts\node2vec\emb\Covid\mers\39.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\4.edgelist --output scripts\node2vec\emb\Covid\mers\4.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\41.edgelist --output scripts\node2vec\emb\Covid\mers\41.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\42.edgelist --output scripts\node2vec\emb\Covid\mers\42.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\43.edgelist --output scripts\node2vec\emb\Covid\mers\43.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\44.edgelist --output scripts\node2vec\emb\Covid\mers\44.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\45.edgelist --output scripts\node2vec\emb\Covid\mers\45.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\46.edgelist --output scripts\node2vec\emb\Covid\mers\46.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\47.edgelist --output scripts\node2vec\emb\Covid\mers\47.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\48.edgelist --output scripts\node2vec\emb\Covid\mers\48.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\49.edgelist --output scripts\node2vec\emb\Covid\mers\49.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\5.edgelist --output scripts\node2vec\emb\Covid\mers\5.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\50.edgelist --output scripts\node2vec\emb\Covid\mers\50.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\54.edgelist --output scripts\node2vec\emb\Covid\mers\54.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\56.edgelist --output scripts\node2vec\emb\Covid\mers\56.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\57.edgelist --output scripts\node2vec\emb\Covid\mers\57.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\58.edgelist --output scripts\node2vec\emb\Covid\mers\58.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\59.edgelist --output scripts\node2vec\emb\Covid\mers\59.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\60.edgelist --output scripts\node2vec\emb\Covid\mers\60.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\61.edgelist --output scripts\node2vec\emb\Covid\mers\61.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\62.edgelist --output scripts\node2vec\emb\Covid\mers\62.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\63.edgelist --output scripts\node2vec\emb\Covid\mers\63.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\65.edgelist --output scripts\node2vec\emb\Covid\mers\65.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\66.edgelist --output scripts\node2vec\emb\Covid\mers\66.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\67.edgelist --output scripts\node2vec\emb\Covid\mers\67.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\68.edgelist --output scripts\node2vec\emb\Covid\mers\68.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\69.edgelist --output scripts\node2vec\emb\Covid\mers\69.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\7.edgelist --output scripts\node2vec\emb\Covid\mers\7.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\70.edgelist --output scripts\node2vec\emb\Covid\mers\70.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\71.edgelist --output scripts\node2vec\emb\Covid\mers\71.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\72.edgelist --output scripts\node2vec\emb\Covid\mers\72.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\73.edgelist --output scripts\node2vec\emb\Covid\mers\73.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\74.edgelist --output scripts\node2vec\emb\Covid\mers\74.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\75.edgelist --output scripts\node2vec\emb\Covid\mers\75.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\76.edgelist --output scripts\node2vec\emb\Covid\mers\76.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\77.edgelist --output scripts\node2vec\emb\Covid\mers\77.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\79.edgelist --output scripts\node2vec\emb\Covid\mers\79.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\8.edgelist --output scripts\node2vec\emb\Covid\mers\8.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\80.edgelist --output scripts\node2vec\emb\Covid\mers\80.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\81.edgelist --output scripts\node2vec\emb\Covid\mers\81.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\82.edgelist --output scripts\node2vec\emb\Covid\mers\82.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\83.edgelist --output scripts\node2vec\emb\Covid\mers\83.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\84.edgelist --output scripts\node2vec\emb\Covid\mers\84.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\85.edgelist --output scripts\node2vec\emb\Covid\mers\85.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\86.edgelist --output scripts\node2vec\emb\Covid\mers\86.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\87.edgelist --output scripts\node2vec\emb\Covid\mers\87.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\88.edgelist --output scripts\node2vec\emb\Covid\mers\88.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\89.edgelist --output scripts\node2vec\emb\Covid\mers\89.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\9.edgelist --output scripts\node2vec\emb\Covid\mers\9.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\90.edgelist --output scripts\node2vec\emb\Covid\mers\90.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\91.edgelist --output scripts\node2vec\emb\Covid\mers\91.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\92.edgelist --output scripts\node2vec\emb\Covid\mers\92.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\93.edgelist --output scripts\node2vec\emb\Covid\mers\93.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\94.edgelist --output scripts\node2vec\emb\Covid\mers\94.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\97.edgelist --output scripts\node2vec\emb\Covid\mers\97.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\98.edgelist --output scripts\node2vec\emb\Covid\mers\98.emb
python scripts\node2vec\src\main.py --input datasets\processed\6\node2vec\Covid\mers\99.edgelist --output scripts\node2vec\emb\Covid\mers\99.emb